version: 2.1

commands:
  print_pipeline_id:
    description: "Learning can be fun"
    parameters:
      to:
        type: string
        default: "Hello World"
    steps:
      - run: echo ${CIRCLE_WORKFLOW_ID}

jobs:
  save_hello_world_output:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          command: |
            echo "hello Onoh Somtochukwu" > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt

  print_output_file:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - attach_workspace:
          at: ~/
      - run: cat ~/output.txt

  sayhello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - print_pipeline_id:

workflows:
  say-hello-workflow:
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
      - sayhello
