version: 2.1

jobs:
  save_hello_world_output:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          command: echo "hello Onoh Somtochukwu" > output.txt
      - persist_to_workspace:
        root: /temp/dir
        paths:
          - output.txt

workflows:
  say-hello-workflow:
    jobs:
      - save_hello_world_output
