version: 2.1

jobs:
  print_hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          command: echo "Hello"

  print_name:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          # This prints my name
          command: |
            echo $MY_NAME 

workflows:
  say-hello-workflow:
    jobs:
      - print_hello
      - print_name:
          requires:
            # indentation error
            - print_hello
